MOSIP-23833
mosip/commons pull request #1428
Opened 2023-05-04 12:19 UTC by ckm007

2023-05-11 08:37 UTC, sowmya695 requested changes
Please check the comment

2023-05-11 08:37 UTC, sowmya695 commented on db_upgrade_scripts/mosip_kernel/sql/1.1.5.5_to_1.2.0.1-B1_upgrade.sql
In this file still these tables are present in release branch.Why we are dropping the tables ?

2023-05-11 11:15 UTC, sowmya695 commented on db_upgrade_scripts/mosip_kernel/sql/1.1.5.5_to_1.2.0.1-B1_upgrade.sql
mosip_authdevice and mosip_regdevice data base changes are there in release-1.2.0.1 branch but you have created db_upgrade_scripts folder for that.whether these moved to any other repo?

2023-05-15 09:52 UTC, vishwa-vyom commented on db_upgrade_scripts/mosip_kernel/sql/1.1.5.5_to_1.2.0.1-B1_upgrade.sql
> +DROP TABLE IF EXISTS kernel.dao_key_store CASCADE;
As per 1.1.5.5 I don't see these tables in mosip_kernel, so we have to remove this section completely

2023-05-15 09:53 UTC, vishwa-vyom commented on db_upgrade_scripts/mosip_kernel/sql/1.1.5.5_to_1.2.0.1-B1_upgrade.sql
In LTS, I think both regdevice and authdevice has be moved inside pms, so these dbs are no more required.

2023-05-15 09:53 UTC, vishwa-vyom approved these changes

2023-05-15 09:53 UTC, merged