creating restTemplate object in postconstruct
mosip/commons pull request #701
Opened 2021-02-15 04:41 UTC by Ajay1596

2021-02-15 07:43 UTC, gsasikumar requested changes

2021-02-15 07:43 UTC, gsasikumar commented on kernel/kernel-auth-adapter/src/main/java/io/mosip/kernel/auth/defaultadapter/handler/AuthHandler.java
>  	private static final String DEFAULTADMIN_MOSIP_IO = "defaultadmin@mosip.io";
What is this? I know u have not changed but why is it not in configuration with this as a default value? if this is not used please remove it.

2021-02-15 07:43 UTC, gsasikumar commented on kernel/kernel-auth-adapter/src/main/java/io/mosip/kernel/auth/defaultadapter/handler/AuthHandler.java
> +		return authentication == null ? DEFAULTADMIN_MOSIP_IO : authentication.getName();
why should it give this user? why not throw an exception? or send empty? What's the use of this?

2021-02-15 07:43 UTC, gsasikumar commented on kernel/kernel-auth-adapter/src/main/java/io/mosip/kernel/auth/defaultadapter/handler/AuthHandler.java
>  	public void addCorsFilter(HttpServer httpServer, Vertx vertx) {
what CORS is it? rename this method to make sense.

2021-02-15 07:45 UTC, gsasikumar commented
@Ajay1596 also have you checked the expiry of token scenario?

2022-02-14 09:11 UTC, urviljoshi commented
closed as discussed with @gsasikumar

2022-02-14 09:11 UTC, closed without merging